version: '3.7'

services:
  api-project-c:
    build: .
    container_name: api-project-c
    environment:
      HOST: ${HOST}
      USER: ${USER}
      PASSWORD: ${PASSWORD}
      DATABASE: ${DATABASE}
    ports:
      - "8000:8000"

  db-project-c-mysql:
    image: mysql:8.0.19
    container_name: db-project-c-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql