#ifndef GAME_H
#define GAME_H

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600
#define LIMIT_BLOCK 10
#define BLOCK_TO_REMOVE 4
#define MAX_TIME_TO_LAUNCH_SERVER 3
#define MAX_TIME_SLEEP_TO_RETRY_ENTER_SERVER 2
#define HEIGHT_BLOCK 30
#define WIDTH_BLOCK 10
#define SIZE_BLOCK 20
#define FPS 40
#endif

